=== MicrosoftWindows96/COMP2211---Runway-Redeclaration-Tool/src/main/resources/XML/newAirport.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Models">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Airport">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Runways">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Runway" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="ParallelRunways">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element name="ParallelRunway" maxOccurs="3">
                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="LogicalRunway" maxOccurs="2">
                                        <xs:complexType>
                                          <xs:sequence>
                                            <xs:element name="stopway" type="xs:integer"/>
                                            <xs:element name="clearway" type="xs:integer"/>
                                            <xs:element name="TORA" type="xs:integer"/>
                                            <xs:element name="dispThresh" type="xs:integer"/>
                                          </xs:sequence>
                                          <xs:attribute name="degree" type="xs:string" use="required"/>
                                        </xs:complexType>
                                      </xs:element>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="code" type="xs:string" use="required"/>
            <xs:attribute name="name" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== MicrosoftWindows96/COMP2211---Runway-Redeclaration-Tool/src/main/resources/XML/testAirports.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Models xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="newAirport.xsd">
    <Airport code="ANT" name="Anthony">
        <Runway>
            <LogicalRunway degree="09">
                <direction>L</direction>
                <stopway>0</stopway>
                <clearway>0</clearway>
                <TORA>3660</TORA>
                <dispThresh>0</dispThresh>
            </LogicalRunway>
        </Runway>
    </Airport>
</Models>
